### Site Settings ###
title               : Adithya Anand
description         : >-                                    # >- means to ignore newlines until "url:"
                      Software Engineer @ Amazon


url                 : ""                                    # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
abouturl            : https://adi10197.github.io/about/
repository          : adi10197/adi10197.github.io   # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]

### Author Info ###
author:
  name              : Adithya Anand
#  image             : ../assets/img/space-invaders.jpg
# behance           : your_username
# dribbble          : your_username
  email             : n.adithya10197@gmail.com
#  facebook          : sahibs99
  github            : adi10197
# gitlab            : your_username
#  instagram         : insta_handle
  linkedin          : anandadithya
#  medium            : medium_handle
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : vogonGeneral
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
